services:
  talenhuman-api:
    build:
      context: .
      dockerfile: src/TalenHuman.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST:-172.17.0.1};Port=${DB_PORT:-5432};Database=TalenHuman;Username=postgres;Password=${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  talenhuman-web:
    build:
      context: .
      dockerfile: src/TalenHuman.Web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - talenhuman-api
