services:
  talenhuman-api:
    build:
      context: .
      dockerfile: src/TalenHuman.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=172.17.0.1;Port=5432;Database=TalenHuman;Username=postgres;Password=postgres
    ports:
      - "5001:8080"
    volumes:
      - .:/app

  talenhuman-web:
    build:
      context: .
      dockerfile: src/TalenHuman.Web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - talenhuman-api
